FROM centos:centos7

RUN yum -y update && yum clean all
RUN yum install -y which
RUN yum install -y wget
RUN yum install -y tar
RUN yum install -y vim
RUN yum install -y git
RUN yum -y install openssh-server openssh-clients

ENV LOGIN_PATH password

RUN echo $LOGIN_PATH | passwd --stdin root

RUN ssh-keygen -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
RUN sed -ri 's/^UsePAM yes/UsePAM no/' /etc/ssh/sshd_config
RUN sed -ri 's/^#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 10022

CMD ["/usr/sbin/sshd", "-D"]
