# OS
FROM centos:centos7

# Base
RUN yum install -y gcc libffi-devel python-devel openssl-devel epel-release sshpass
RUN yum install -y openssh-server openssh-clients
RUN curl -kL https://bootstrap.pypa.io/get-pip.py | python

# Ansible Install
RUN pip install ansible

